### ISSUE TITLE
docker serverにimageを作成

### ISSUE THREAD

**Issue by cappyzawa** [kutsuzawa/hyakkiyako#7]
docker sdk使って頑張る
現状ではどうやって使うかするわからない

https://docs.docker.com/engine/api/get-started/
ここがとっかかりやすい

フルドキュメントは
https://godoc.org/github.com/moby/moby/client

**Comment by shu920921** [comment]
imageのbuildは https://godoc.org/github.com/moby/moby/client#Client.ImageBuild
